# Generated by Django 5.0.4 on 2024-05-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_date_review_created_date_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
    ]
