# Generated by Django 5.0.4 on 2024-10-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
