# Generated by Django 5.1.1 on 2024-10-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_like_created_at_alter_like_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
